language: ruby

import:
  - travis-ci/build-configs/db-setup.yml

rvm: 2.5.1

script: "bundle exec rake knapsack:rspec"
env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000
    - CI_NODE_TOTAL=3

cache: bundler

services:
  - redis-server

before_install:
  - 'gem update --system'

jobs:
  include:
    - env: CI_NODE_INDEX=0
      rvm: 2.5.1
    - env: CI_NODE_INDEX=1
      rvm: 2.5.1
    - env: CI_NODE_INDEX=2
      rvm: 2.5.1
    - stage: ":ship: it to Quay.io"
      sudo: required
      install: skip
      before_script: skip
      before_install: skip
      script: ./script/docker-build-and-push