language: ruby

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - 'gem update --system'

services:
  - postgresql

addons:
  postgresql: "11.2"

rvm: 2.5.1

script: "bundle exec rake knapsack:rspec"
env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000
    - CI_NODE_TOTAL=3

  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2

cache: bundler

services:
  - redis-server
  - postgresql

before_script:
  - psql --version
  - psql -c 'CREATE DATABASE travis_test;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - createdb travis_test || true
  - curl -fs https://raw.githubusercontent.com/travis-ci/travis-migrations/master/db/main/structure.sql | psql travis_test


jobs:
  include:
    - stage: ":ship: it to Quay.io"
      install: echo skip
      before_script: echo skip
      script: make ship
