language: ruby

# Disable shared config to test pg 10 as CI isn't set up within the
# build-configs repo itself.
# import:
#   - travis-ci/build-configs/db-setup.yml
addons:
  postgresql: 10
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

services:
  - postgresql

rvm: 2.5.1

script: "bundle exec rake knapsack:rspec"
env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000
    - CI_NODE_TOTAL=3

  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2

cache: bundler

services:
  - redis-server

before_install:
  - 'gem update --system'

before_script:
  - createdb travis_test || true
  - curl -fs https://raw.githubusercontent.com/travis-ci/travis-migrations/master/db/main/structure.sql | psql travis_test


jobs:
  include:
    - stage: ":ship: it to Quay.io"
      install: echo skip
      before_script: echo skip
      script: make ship
