language: ruby

import:
  - travis-ci/build-configs:db-setup.yml

rvm: 2.6.5

script: "bundle exec rspec spec"

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000

cache: bundler

services:
  - redis-server

before_install:
  - 'gem update --system'

jobs:
  include:
    - stage: "Test"
    - stage: ":ship: it to Quay.io"
      install: echo skip
      before_script: echo skip
      script: make ship
      if: type = cron OR commit_message =~ /ship:docker/ OR env(SHIP_DOCKER) = true
